- repo: local
  hooks:
    - id: mix-compile
      name: 'elixir: compiling'
      entry: mix compile --warnings-as-errors
      language: system
      files: \.ex$
      pass_filenames: false
    - id: mix-test
      name: 'elixir: running tests'
      entry: mix test
      language: system
      files: \.exs$
    - id: mix-format
      name: 'elixir: checking formatting'
      entry: mix format --check-formatted
      language: system
      files: \.exs?$
    - id: dialyzer
      name: 'elixir: dialyzer'
      entry: mix dialyzer
      language: system
      files: \.ex$
- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: master
  hooks:
    - id: trailing-whitespace
    - id: check-merge-conflict
